name: CI-CD

on:
  push:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet publish Api/Api.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: TEST-2-CICD
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: publish


# postgresql://postgres:[YOUR-PASSWORD]@db.hbegfncpybgpsgevztfj.supabase.co:5432/postgres
# 4Aq9?6ZMTV_cb93